spring:
  application:
    name: order80zk
  profiles:
    active: dev #默认为开发环境
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username: lc
    password: love971968504.
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

server:
  port: 80


mybatis:
  mapper-locations:
    #- classpath:com.**.mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: com.lc.order.entities


