spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        dsl:
          nacos:
            serverAddr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            dataType: json
            #流控规则
            ruleType: flow
        ds2:
          nacos:
            serverAddr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            dataType: json
            #流控规则
            ruleType: degrade

  #spring-boot 2.6后不推荐循环依赖
  main:
    allow-circular-references: true

server:
  port: 9007

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true



