spring:
  application:
    name: rabbitmq-5691
  rabbitmq:
    host: 192.168.31.203
    port: 5672
    username: admin
    password: password
    publisher-confirm-type: correlated
    #发布退回
    publisher-returns: true
server:
  port: 5691


