spring:
  application:
    name: seata-order
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/seata_order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}
  service:
    vgroup-mapping:
      default: default
  config:
    type: file
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username:
      password:

mybatis:
  mapper-locations:
    #- classpath:com.**.mapper/*.xml
    - classpath*:com/**/mapper/*.xml